# Generated by Django 5.2.17 on 2026-10-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='unique_session_name_per_school'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('school',), name='one_current_session_per_school'), models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='session_end_after_start')],
            },
        ),
    ]
