# Generated by Django 5.2.17 on 2026-10-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='academics.academicsession')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('session', 'name'), name='unique_period_name_per_session'), models.UniqueConstraint(fields=('session', 'order'), name='unique_period_order_per_session'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('school',), name='one_current_period_per_school'), models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='period_end_after_start')],
            },
        ),
    ]
